#! /bin/sh
### BEGIN INIT INFO
# Provides:          pi-beacon
# Required-Start:    $remote_fs $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: UPNP announce
### END INIT INFO


DAEMON_UID=lp
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DAEMON_NAME=pi-beacon
DIR=/var/lib/${DAEMON_NAME}
DAEMON=${DIR}/${DAEMON_NAME}.py
DAEMON_ARGS="-l"
[ -x "$DAEMON" ] || exit 0
DESC="UPNP announce"
NAME="pi-beacon.py"

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid


. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
    	start-stop-daemon --start --background --chuid $DAEMON_UID --chdir $DIR -pidfile $PIDFILE --make-pidfile --exec  $DAEMON  -- $DAEMON_ARGS
	log_end_msg $?
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
#    status)
#	status_of_proc -p $PIDFILE $NAME $DAEMON && exit 0 || exit $?
#	;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
	# start-stop-daemon --stop --pidfile $PIDFILE --retry 10
	start-stop-daemon --oknodo --stop --quiet --name pi-beacon.py
	log_end_msg $?
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
